[package]
  cjc-version = "1.1.0"
  name = "game_demo"
  organization = ""
  description = "Original farm-sim example for termcanvas"
  version = "1.0.0"
  target-dir = ""
  script-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = "--whole-archive -l:libclang_rt-profile.a --no-whole-archive"
  package-configuration = {}

[dependencies]
  "core" = { path = "../../packages/core", output-type = "static" }
