#!/usr/bin/env python3
import argparse
import difflib
from pathlib import Path


VERSION = "17.0.0"
DEFAULT_INPUT_DIR = Path("packages/core/tests/unicode") / VERSION
DEFAULT_OUTPUT = Path("packages/core/src/unicode_data.cj")

GCB_NAMES = [
    "Other",
    "CR",
    "LF",
    "Control",
    "Extend",
    "ZWJ",
    "Regional_Indicator",
    "Prepend",
    "SpacingMark",
    "L",
    "V",
    "T",
    "LV",
    "LVT",
]

INCB_ENUM_NAMES = [
    "InCBNone",
    "Consonant",
    "Extend",
    "Linker",
]

INCB_PROPERTY_NAMES = [
    "Consonant",
    "Extend",
    "Linker",
]


def parse_range(raw):
    if ".." in raw:
        start, end = raw.split("..", 1)
    else:
        start = end = raw
    return int(start, 16), int(end, 16)


def parse_semicolon_ranges(path, wanted):
    ranges = {key: [] for key in wanted}
    for line in path.read_text(encoding="utf-8").splitlines():
        body = line.split("#", 1)[0].strip()
        if not body or ";" not in body:
            continue
        fields = [part.strip() for part in body.split(";")]
        code_range = fields[0]
        prop = fields[1] if len(fields) == 2 else f"{fields[1]}; {fields[2]}"
        if prop in ranges:
            ranges[prop].append(parse_range(code_range))
    return {key: merge_ranges(value) for key, value in ranges.items()}


def merge_ranges(ranges):
    if not ranges:
        return []
    ordered = sorted(ranges)
    merged = [ordered[0]]
    for start, end in ordered[1:]:
        prev_start, prev_end = merged[-1]
        if start <= prev_end + 1:
            merged[-1] = (prev_start, max(prev_end, end))
        else:
            merged.append((start, end))
    return merged


def fmt_u32(value):
    return f"0x{value:04X}u32"


def emit_range_match(name, ranges, default, ascii_default=False):
    lines = [f"func {name}(code: UInt32): {default[0]} {{"]
    if ascii_default:
        lines.append(
            f"    if (code >= 0x0020u32 && code <= 0x007Eu32) {{ return {default[0]}.{default[1]} }}"
        )
    for value_name, value_ranges in ranges:
        if not value_ranges:
            continue
        for start, end in value_ranges:
            lines.append(
                f"    if (code >= {fmt_u32(start)} && code <= {fmt_u32(end)}) {{ return {default[0]}.{value_name} }}"
            )
    lines.append(f"    {default[0]}.{default[1]}")
    lines.append("}")
    lines.append("")
    return lines


def emit_bool_match(name, ranges, ascii_default=False):
    lines = [f"func {name}(code: UInt32): Bool {{"]
    if ascii_default:
        lines.append("    if (code <= 0x007Fu32) { return false }")
    if not ranges:
        lines.append("    false")
    else:
        for start, end in ranges:
            lines.append(
                f"    if (code >= {fmt_u32(start)} && code <= {fmt_u32(end)}) {{ return true }}"
            )
        lines.append("    false")
    lines.append("}")
    lines.append("")
    return lines


def emit_same_func(name, enum_name, variants):
    lines = [f"func {name}(left: {enum_name}, right: {enum_name}): Bool {{", "    match ((left, right)) {"]
    for variant in variants:
        lines.append(f"        case ({variant}, {variant}) => true")
    lines.extend(["        case _ => false", "    }", "}", ""])
    return lines


def generate(input_dir):
    gcb = parse_semicolon_ranges(input_dir / "GraphemeBreakProperty.txt", set(GCB_NAMES))
    incb = parse_semicolon_ranges(
        input_dir / "DerivedCoreProperties.txt",
        {f"InCB; {name}" for name in INCB_PROPERTY_NAMES},
    )
    pict = parse_semicolon_ranges(input_dir / "emoji-data.txt", {"Extended_Pictographic"})

    lines = [
        "package core",
        "",
        f"// Generated by scripts/generate_unicode_tables.py from Unicode {VERSION}.",
        "// Do not edit by hand.",
        "",
        "enum GraphemeBreakClass {",
    ]
    for name in GCB_NAMES:
        lines.append(f"    | {name.replace('_', '')}")
    lines.extend([
        "}",
        "",
        "enum IndicConjunctBreakClass {",
    ])
    for name in INCB_ENUM_NAMES:
        lines.append(f"    | {name}")
    lines.extend([
        "}",
        "",
    ])
    lines.extend(emit_same_func("sameGraphemeBreakClass", "GraphemeBreakClass", [name.replace("_", "") for name in GCB_NAMES]))
    lines.extend(emit_same_func("sameIndicConjunctBreakClass", "IndicConjunctBreakClass", INCB_ENUM_NAMES))

    gcb_ranges = []
    for name in GCB_NAMES:
        enum_name = name.replace("_", "")
        gcb_ranges.append((enum_name, gcb.get(name, [])))
    lines.extend(
        emit_range_match(
            "graphemeBreakClass",
            gcb_ranges,
            ("GraphemeBreakClass", "Other"),
            ascii_default=True,
        )
    )

    incb_ranges = []
    for name in INCB_PROPERTY_NAMES:
        incb_ranges.append((name, incb.get(f"InCB; {name}", [])))
    lines.extend(
        emit_range_match(
            "indicConjunctBreakClass",
            incb_ranges,
            ("IndicConjunctBreakClass", "InCBNone"),
            ascii_default=True,
        )
    )
    lines.extend(
        emit_bool_match(
            "isExtendedPictographic",
            pict.get("Extended_Pictographic", []),
            ascii_default=True,
        )
    )

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-dir", type=Path, default=DEFAULT_INPUT_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    generated = generate(args.input_dir)
    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if current != generated:
            diff = difflib.unified_diff(
                current.splitlines(),
                generated.splitlines(),
                fromfile=str(args.output),
                tofile=f"{args.output} (generated)",
                lineterm="",
            )
            print("\n".join(diff))
            raise SystemExit(1)
        return

    args.output.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
